"""added ChannelAccessToken.refreshed_at

Revision ID: 2ef5e4e9532a
Revises: 9946b77c8044
Create Date: 2026-01-21 17:10:45.053240

"""
from typing import Sequence, Union
from datetime import datetime, timezone

# alembic imports
from alembic import op
import sqlalchemy as sa

# custom imports
import app.db.types

# additional imports


# revision identifiers, used by Alembic.
revision: str = '2ef5e4e9532a'
down_revision: Union[str, Sequence[str], None] = '9946b77c8044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('refreshed_at', app.db.types.AwareDateTime(), server_default=sa.text("'1970-01-01 00:00:00+00'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tokens', 'refreshed_at')
    # ### end Alembic commands ###
