"""added Viewer.join_count

Revision ID: 9946b77c8044
Revises:
Create Date: 2026-01-08 15:04:55.163837

"""
from typing import Sequence, Union

# alembic imports
from alembic import op
import sqlalchemy as sa

# custom imports
import app.db.types

# additional imports


# revision identifiers, used by Alembic.
revision: str = '9946b77c8044'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewers', sa.Column('join_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewers', 'join_count')
    # ### end Alembic commands ###
